name: Create Production Builds

jobs:
  build_ios:
    type: build
    params:
      platform: ios
  submit_ios:
    type: submit
    needs: [build_ios]
    params:
      platform: ios
      build_id: ${ needs.build_ios.output.build_id }
